language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - FFMPEG_STATIC=http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.2014-07-16.tar.gz
  - FFMPEG_STATIC=http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz

before_install:
 - sudo sh -x ./test/install-ffmpeg.sh $FFMPEG_STATIC

script:
 - python setup.py test

notifications:
  email:
    - tomaz+travis@tomaz.me
